export const USERS_COLLECTION = 'Users-dev'
export const USER_STATUSES_COLLECTION = 'UserStatuses'
export const USER_EVENTS_COLLECTION = 'UserEvents'
export const RESTORE_USERS_COLLECTION = 'RestoreUsers'
export const DATES_COLLECTION = 'Dates-dev'
export const PROSPECTS_COLLECTION = 'Prospects-dev'
export const PARAMETERS_COLLECTION = 'Parameters'
export const NEXTS_COLLECTION = 'Nexts-dev'
export const LIKES_COLLECTION = 'Likes-dev'
export const MATCHES_COLLECTION = 'Matches-dev'
export const PHONE_NUMBERS_COLLECTION = 'PhoneNumbers'
export const RDB_CONNECTED = '.info/connected'
export const RDB_ONLINE_REF = (uid: string) => `/online/${uid}`
