export const USERS_COLLECTION = 'Users-dev'
export const DATES_COLLECTION = 'Dates-dev'
export const PROSPECTS_COLLECTION = 'Prospects-dev'
export const PARAMETERS_COLLECTION = 'Parameters'
export const NEXTS_COLLECTION = 'Nexts-dev'
export const LIKES_COLLECTION = 'Likes-dev'
export const MATCHES_COLLECTION = 'Matches-dev'
export const PHONE_NUMBERS_COLLECTION = 'PhoneNumbers'
